apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-cart-app
  template:
    metadata:
      labels:
        app: shopping-cart-app
    spec:
      containers:
      - name: frontend
        image: youracr.azurecr.io/shopping-cart-frontend:latest
        ports:
        - containerPort: 80
      - name: backend
        image: youracr.azurecr.io/shopping-cart-backend:latest
        ports:
        - containerPort: 5000
