apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service
spec:
  selector:
    app: shopping-cart-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: frontend
      nodePort: 30000 # Define a static port for the frontend
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: backend
      nodePort: 30001 # Define a static port for the backend
  type: NodePort
